- name: Add longhorn repository to Helm
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    force_update: true

- name: Create namespace for longhorn
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: longhorn-system
    state: present
    kubeconfig: /home/{{ ansible_user }}/.kube/config

- name: Install longhorn using Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: '1.10.1'
    namespace: longhorn-system
    create_namespace: false
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
