- name: Add longhorn repository to Helm
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Create namespace for longhorn
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: longhorn-system
    state: present
    kubeconfig: /home/{{ ansible_user }}/.kube/config

- name: Install longhorn using Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: '1.10.1'
    namespace: longhorn-system
    create_namespace: false
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    wait: true

- name: Hash Longhorn basic-auth password
  ansible.builtin.shell: |
    printf "{{ longhorn_auth_user }}:$(openssl passwd -apr1 '{{ longhorn_auth_password }}')"
  register: longhorn_basic_auth
  no_log: true

- name: Set up Longhorn basic-auth
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: basic-auth
        namespace: longhorn-system
      type: Opaque
      stringData:
        auth: '{{ longhorn_basic_auth.stdout }}'

- name: Create Longhorn ingress with basic auth
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: longhorn-ingress
        namespace: longhorn-system
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
          nginx.ingress.kubernetes.io/proxy-body-size: 10000m
          cert-manager.io/cluster-issuer: letsencrypt-prod
      spec:
        tls:
          - hosts:
              - longhorn.sys.larsverschoor.nl
            secretName: longhorn-tls
        ingressClassName: nginx
        rules:
          - host: longhorn.sys.larsverschoor.nl
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: longhorn-frontend
                      port:
                        number: 80
