- name: Add ingress-nginx repository to Helm
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Create namespace for ingress-nginx
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: ingress-nginx
    state: present
    kubeconfig: /home/{{ ansible_user }}/.kube/config
