$ANSIBLE_VAULT;1.1;AES256
62303431386332346632623439636566313338353632376664386230333263323131333430636462
3662383730656639393738323265323664363139383638620a663031353436653430386634303162
63633366633638636638666634396639623066353366396639383963386261366366386133623138
3165303136303938340a393533333463393666316434366638636333653165626462346630626662
39376237613934303262323838363363396335633138666636316233643462656339
