- name: Add ArgoCD repository to Helm
  kubernetes.core.helm_repository:
    name: argocd
    repo_url: https://argoproj.github.io/argo-helm

- name: Create namespace for ArgoCD
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present
    kubeconfig: /home/{{ ansible_user }}/.kube/config

- name: Install ArgoCD using Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argocd/argo-cd
    namespace: argocd
    create_namespace: false
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    wait: true
    values:
      server:
        extraArgs:
          - --insecure

- name: Hash ArgoCD basic-auth password
  ansible.builtin.shell: |
    printf "{{ argocd_auth_user }}:$(openssl passwd -apr1 '{{ argocd_auth_password }}')"
  register: argocd_basic_auth
  no_log: true

- name: Set up ArgoCD basic-auth
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: basic-auth
        namespace: argocd
      type: Opaque
      stringData:
        auth: '{{ argocd_basic_auth.stdout }}'

- name: Create ArgoCD ingress with basic auth
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: argocd-ingress
        namespace: argocd
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
          nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
          nginx.ingress.kubernetes.io/proxy-body-size: 10000m
          cert-manager.io/cluster-issuer: letsencrypt-prod
      spec:
        tls:
          - hosts:
              - argocd.sys.larsverschoor.nl
            secretName: argocd-tls
        ingressClassName: nginx
        rules:
          - host: argocd.sys.larsverschoor.nl
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: argocd-server
                      port:
                        number: 80

- name: Create Argo CD GitHub repo credential
  kubernetes.core.k8s:
    state: present
    namespace: argocd
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitops-repo-credentials
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        url: 'https://github.com/LarsVerschoor/GitOps'
        username: '{{ github_username }}'
        password: '{{ github_pat }}'

- name: Apply all Argo CD Applications
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    namespace: argocd
    src: '{{ item.path }}'
  with_filetree: argocd/applications
  when: item.state == 'file'
