- name: Add ArgoCD repository to Helm
  kubernetes.core.helm_repository:
    name: argocd
    repo_url: https://argoproj.github.io/argo-helm

- name: Create namespace for ArgoCD
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present
    kubeconfig: /home/{{ ansible_user }}/.kube/config

- name: Install ArgoCD using Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argocd
    namespace: argocd
    create_namespace: false
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    wait: true
    values:
      server:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - argocd.sys.larsverschoor.nl
